name: Custom

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git credentials
        run: |
          git config --global user.email "yuneshshrestha24@gmail.com"
          git config --global user.name "GitHub Action"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run custom action
        uses: YuneshShrestha/custom-action@main
